version: 2.1

workflows:
  pr:
    jobs:
      - lint:
          filters:
            branches:
              ignore:
                - main
      - test:
          filters:
            branches:
              ignore:
                - main

  merge:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - deploy:
          context: aws-excom-deploy
          requires:
            - test
          filters:
            branches:
              only: main

commands:
  install-package-deploy:
    description: "Build and install package"
    steps:
      - run: pip install .[deploy]
  install-package-dev:
    description: "Build and install package"
    steps:
      - run: pip install .[dev]

jobs:
  lint:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - install-package-dev
      - run:
          name: Lint
          command: black --check aws_excom

  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - install-package-dev
      - run:
          name: Run python tests
          command: pytest -v

  deploy:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - install-package-deploy
      - run:
          name: Deploy package
          command: python deploy.py
